Test06_Ajax/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Test06_Ajax.Models
{
    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Role Role { get; set; }


    }
    public enum Role
    {
        Admin,
        User,
        Guest
    }
}

Test06_Ajax/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test06_Ajax.Services;

namespace Test06_Ajax.Controllers
{
    public partial class HomeController : Controller
    {
        private readonly IAlaki _alaki;
        public HomeController(IAlaki alaki)
        {
            _alaki = alaki;
        }
        public virtual ActionResult Index()
        {
            _alaki.Add(3);
            return View();
        }

        public virtual ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public virtual ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Test06_Ajax/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test06_Ajax.Models;

namespace Test06_Ajax.Controllers
{
    public partial class PeopleController : Controller
    {
        private Person[] personData = {
                new Person {FirstName = "Adam", LastName = "Freeman", Role = Role.Admin},
                new Person {FirstName = "Jacqui", LastName = "Griffyth", Role= Role.User},
                new Person {FirstName = "John", LastName = "Smith", Role = Role.User},
                new Person {FirstName = "Anne", LastName = "Jones", Role = Role.Guest}
        };
        // GET: Pople
        public virtual ActionResult Index()
        {
            return View();
        }
        public virtual ActionResult GetPeople()
        {
            return View();
        }


        //[HttpPost]
        //public ActionResult GetPeople(string selectedRole)
        //{
        //    if (selectedRole == null || selectedRole == "All")
        //    {
        //        return View(personData);
        //    }
        //    else
        //    {
        //        Role selected = (Role)Enum.Parse(typeof(Role),
        //        selectedRole);
        //        return View(personData.Where(p => p.Role == selected));
        //    }
        //}

        public virtual PartialViewResult GetPeopleData(string selectedRole = "All")
        {
            IEnumerable<Person> data = personData;
            if (selectedRole != "All")
            {
                Role selected = (Role)Enum.Parse(typeof(Role),
                selectedRole);
                data = personData.Where(p => p.Role == selected);
            }
            return PartialView(data);
        }
        //public ActionResult GetPeople(string selectedRole = "All")
        //{
        //    return View((object)selectedRole);
        //}

    }
}

Test06_Ajax/Controllers/RedActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Test06_Ajax.Controllers
{
    public class RedActorController : Controller
    {
        // GET: RedActor
        public ActionResult Index()
        {
            return View();
        }
    }
}

Test06_Ajax/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>


<p>Use this area to provide additional information.</p>

Test06_Ajax/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>



<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Test06_Ajax/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

@*@Html.YouTubePlayer("Casablanca", "iLdqKUkkM6w", new YouTubePlayerOption()
    {
    Border = true
    })*@

@*<video controls="controls">
    <source src="https://www.aparat.com/4f1f5119-92f0-48f6-983c-f24f77dce50f" type="video/mp4" />
</video>*@

@*<embed height="400" width="500"
       flashvars="config=http://www.aparat.com//video/video/config/videohash/BA9Md/watchtype/embed"
       allowfullscreen="true"
       quality="high" name="aparattv_BA9Md" id="aparattv_BA9Md"
       src="https://www.aparat.com/public/player/aparattv" type="application/x-shockwave-flash">*@



@*<embed height="400" width="500"
       flashvars="config=http://www.aparat.com//video/video/config/videohash/BA9Md/watchtype/embed"
       allowfullscreen="true"
       quality="high" name="aparattv_BA9Md" id="aparattv_BA9Md"
       src="http://host10.aparat.com/public/player/aparattv" type="application/x-shockwave-flash">*@

Test06_Ajax/Views/People/GetPeople.cshtml
@using Test06_Ajax.Models
@model string
@{
    ViewBag.Title = "GetPeople";
    Layout = "/Views/Shared/_Layout.cshtml";
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        UpdateTargetId = "tableBody",
        Url = Url.Action(MVC.People.GetPeopleData()),
        LoadingElementId = "loading",
        LoadingElementDuration = 1000,
        // Confirm = "Do you wish to request new data?"
    };
}
<h2>Get People</h2>
<div id="loading" class="load" style="display:none">
    <p>Loading Data...</p>
</div>
<table>
    <thead><tr><th>First</th><th>Last</th><th>Role</th></tr></thead>
    <tbody id="tableBody">
        @Html.Action(MVC.People.GetPeopleData(selectedRole:Model))
    </tbody>
</table>
@using (Ajax.BeginForm(ajaxOpts))
{
    <div>
        

            @Html.DropDownList("selectedRole", new SelectList(
        new [] {"All"}.Concat(Enum.GetNames(typeof(Role)))),new { id="aa"})


        <button id="bb" type="submit">Submit</button>
    </div>
}
@section script{

    <script>
        $(document).ready(function () {
            $("#aa").change(function () {
                
                @*var val1 = document.getElementById("aa").value;
                
                @{Html.RenderAction("GetPeopleData",  new { selectedRole =}  );}*@
                document.getElementById("bb").click();
                
            });
        });
    </script>
}

Test06_Ajax/Views/People/GetPeopleData.cshtml
@using Test06_Ajax.Models
@model IEnumerable<Person>
@foreach (Person p in Model)
{
    <tr>
        <td>@p.FirstName</td>
        <td>@p.LastName</td>
        <td>@p.Role</td>
    </tr>
}

Test06_Ajax/Views/People/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "/Views/Shared/_Layout.cshtml";
}<h2>Basic Links & URLs</h2>
<table>
    <thead><tr><th>Helper</th><th>Output</th></tr></thead>
    <tbody>
        <tr>
            <td>@Url.Content(Links.Content.Site_css)</td>
            <td>@Url.Content(Links.Content.Site_css)</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("My Link", MVC.Home.Index())</td>
            <td>@Html.ActionLink("My Link", MVC.Home.Index())</td>
        </tr>
        <tr>
            <td>Url.Action("GetPeople", "People")</td>
            <td>@Url.Action(MVC.People.GetPeople())</td>
        </tr>
        <tr>
            <td>
                @Url.RouteUrl(new { controller = "People", action = "GetPeople" })
            </td>
            <td>
                @Url.RouteUrl(new { controller = "People", action = "GetPeople" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.RouteLink("My Link", MVC.People.GetPeople())
            </td>
            <td>
                @Html.RouteLink("My Link", new { controller = "People", action = "GetPeople" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.RouteLink("My Link", "FormRoute", new { controller = "People", action = "GetPeople" })
            </td>
            <td>
                @*@Html.RouteLink("My Link", "FormRoute", new {controller ="People",action="GetPeople"})*@
            </td>
        </tr>
    </tbody>
</table>
<br />
<br />
<br />
<br />
<textarea id="redactor_content" name="content"></textarea>

@section script{

    <script type="text/javascript">
        $(document).ready(
            function () {
                $('#redactor_content').redactor();
            }
        );
    </script>

}

Test06_Ajax/Views/RedActor/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Redactor</title>
    <meta charset="utf-8">

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <link rel="stylesheet" href="~/Content/redactor/redactor.css" />
    <script src="~/Scripts/redactor/redactor.min.js"></script>

    <script type="text/javascript">
    		$(document).ready(
    			function()
    			{
    				$('#redactor_content').redactor();
    			}
    		);
    </script>
</head>
<body>
    <textarea id="redactor_content" name="content"></textarea>
</body>
</html>

Test06_Ajax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        label {
            display: inline-block;
            width: 100px;
        }

        div.dataElem {
            margin: 5px;
        }

        h2 > label {
            width: inherit;
        }

        .editor-label, .editor-field {
            float: left;
            margin-top: 10px;
        }

            .editor-field input {
                height: 20px;
            }

        .editor-label {
            clear: left;
        }

        .editor-field {
            margin-left: 10px;
        }

        input[type=submit] {
            float: left;
            clear: both;
            margin-top: 10px;
        }

        .column {
            float: left;
            margin: 10px;
        }

        table, td, th {
            border: thin solid black;
            border-collapse: collapse;
            padding: 5px;
            background-color: lemonchiffon;
            text-align: left;
            margin: 10px 0;
        }

        div.load {
            color: red;
            margin: 10px 0;
            font-weight: bold;
        }

        div.ajaxLink {
            margin-top: 10px;
            margin-right: 5px;
            float: left;
        }
    </style>
    <link rel="stylesheet" href="~/Content/redactor/redactor.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/redactor/redactor.min.js"></script>
    @RenderSection("script", false)
</body>
</html>